CREATE TABLE READING (
  ID          BIGSERIAL,
  INSERTED_TIME TIMESTAMP      NOT NULL,
  KWH_VALUE   NUMERIC(19, 8) NOT NULL,
  METER_ID    BIGINT         NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (METER_ID) REFERENCES METER (ID)
);

CREATE INDEX READING_INDEX
  ON READING (
    ID
  )