CREATE TABLE READING (
  ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
  LIGHT_VALUE  INT                                 NULL,
  LIGHT_RATIO  DECIMAL(10, 2)                      NULL,
  READING_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  METER_ID     BIGINT                              NOT NULL,
  KWH_VALUE    DECIMAL(10, 8)                      NOT NULL
);

CREATE INDEX ID_INDEX ON READING (
  ID,
  READING_TIME
)