CREATE TABLE BLINK (
  ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
  LIGHT_VALUE INT                                 NULL,
  LIGHT_RATIO DECIMAL(10, 2)                      NULL,
  INSERT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  METER_ID    BIGINT                              NOT NULL,
  KWH_VALUE   DECIMAL(10, 8)                      NOT NULL
);

CREATE INDEX BLINK_INDEX
  ON BLINK (
    ID,
    INSERT_TIME
  )