CREATE TABLE READING (
  ID          BIGINT AUTO_INCREMENT,
  INSERT_TIME TIMESTAMP      NOT NULL,
  KWH_VALUE   DECIMAL(19, 8) NOT NULL,
  METER_ID    BIGINT         NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (METER_ID) REFERENCES METER (ID)
);

CREATE INDEX READING_INDEX
  ON READING (
    ID
  )